# Generated by Django 4.0.3 on 2022-05-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='stripe_plan_id',
        ),
        migrations.RemoveField(
            model_name='price',
            name='stripe_price_id',
        ),
    ]
