# Generated by Django 4.0.3 on 2022-03-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_genre', models.CharField(choices=[('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Anime', 'Anime'), ('Romantic Comedy', 'Romantic Comedy'), ('Action', 'Action'), ('Drama', 'Drama')], max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=244)),
                ('movie_description', models.CharField(max_length=500)),
                ('movie_art', models.ImageField(null=True, upload_to='')),
                ('movie_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.moviesgenre')),
            ],
        ),
    ]
