# Generated by Django 4.0.3 on 2022-03-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='movie',
            new_name='movie_name',
        ),
    ]
